spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/users?serverTimezone=UTC
    username: testUser
    password: testPassword
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false